### ISSUE TITLE
Thank you !

### ISSUE THREAD

**Issue by lordvalium** [SpoturDeal/MMM-crypto-portfolio#1]
Thank you for this new module. 
I just wanted to make a pull request with new sparkline IDs but with tortoise i can not commit to the repo. 

Beside the sparklines i wanted to 

-  show additionally the BTC price (when USD is the selected currency for example)
![show two prices](https://user-images.githubusercontent.com/2970225/36095241-a9982486-0ff1-11e8-9563-de0846ec85cf.png)

- format the market cap as this one
![market cap](https://user-images.githubusercontent.com/2970225/36095258-ba5c9a5e-0ff1-11e8-92f1-a61f92ce7b9f.PNG)

I would love to contribute, but i am absolute newbie in this language.. :

**Comment by SpoturDeal** [comment]
I had already added the format for the total marketcap in the latest commit 5 minutes ago.

I do not get what you mean with the BTC code near the sparkline. (sparkline image is only in logo with details)

I do not know jabber. (found out it is not an emailaddress)

**Comment by lordvalium** [comment]
Sorry carl i mixed this up. 
I wanted to commit some  sparkelines (although i am only in detail view). 

And **beside** this  :) i wanted to show again both prices, but i assume that you make this a bit more professional :)
E-Mail adress: detailversessen@mailbox.org ( i will delete it from here after you have read it) 

best regards and thank you a lot

**Comment by SpoturDeal** [comment]
If you make the make sparkline to low (height for a line is about 12px) you can't see the graphic properly
for a proper view you need at least about 50px height.
