### ISSUE TITLE
Nothing displaying..

### ISSUE THREAD

**Issue by anthony6608** [SpoturDeal/MMM-crypto-portfolio#14]
Hi,

First of all thank you for taking the time to create and make this module public. I have followed all the instructions but for some reason I cannot get anything to display. All I see is the heading and nothing else it seems like its stuck and isn't able to retrieve the data. Could you help me out? Thank you!

**Comment by SpoturDeal** [comment]
Hello @anthony6608 ,

Can you please add the config.js you made for this module to your post.

I can probably see what is wrong.

**Comment by anthony6608** [comment]
Hi

Thanks for the response. I just left everything as default to see if it works:

{
	module: "MMM-crypto-portfolio",
	position: "top_right",   // see mirror setting for options
	config: {          // this is changed from Mateo`s Version
		           // enter currency as pairs (name is the coin and portf how much you own)
		currency: [{name: 'bitcoin',  portf:  1.2345678},
		           {name: 'ripple',   portf: 1.688014},
                           {name: 'litecoin', portf: 0.382885},
                           {name: 'ethereum', portf: 3.771212}],
		conversion: 'EUR',
		showPortfolio: true,    
                showAssets: true,       
		showAgainstBTC: true,      // only used in detail view
		showTotalMarketCap: false, // only used in detail view
		showUSD: false,
		fontSize: 'small',
		headers: ['change24h', 'change1h', 'change7d'],
		displayType: 'detail',   // or 'logoWithChanges',
		showGraphs: true,
		limit:100               // increase if your coin doesn't appear ther are more then 1000 
	}
}

**Comment by anthony6608** [comment]
I installed the module, and just simply copied this into my config.js . Is there anything else that needs to be done?

**Comment by SpoturDeal** [comment]
Dit you add a comma behind the last bracket
like this 
`
{
	module: "MMM-crypto-portfolio",
	position: "top_right",   // see mirror setting for options
	config: {          // this is changed from Mateo`s Version
		           // enter currency as pairs (name is the coin and portf how much you own)
		currency: [{name: 'bitcoin',  portf:  1.2345678},
		           {name: 'ripple',   portf: 1.688014},
                           {name: 'litecoin', portf: 0.382885},
                           {name: 'ethereum', portf: 3.771212}],
		conversion: 'EUR',
		showPortfolio: true,    
                showAssets: true,       
		showAgainstBTC: true,      // only used in detail view
		showTotalMarketCap: false, // only used in detail view
		showUSD: false,
		fontSize: 'small',
		headers: ['change24h', 'change1h', 'change7d'],
		displayType: 'detail',   // or 'logoWithChanges',
		showGraphs: true,
		limit:100               // increase if your coin doesn't appear ther are more then 1000 
	}
},

`

Every module is between two brackets { .... },  and a comma behind the closing bracket

**Comment by SpoturDeal** [comment]
Does it work now?

**Comment by SpoturDeal** [comment]
It takes time to develop a module. And I am always happy people to help if there is a problem. One of the pillars of Github is cooperation. Too bad some people don't respond if you try to help them. This issue is closed.

**Comment by anthony6608** [comment]
Hey,

I'm sooo sorry for the delay in response. The past week has been extremely hectic for me but I am back now. I had to end up reinstalling everything on and doing a clean install. I will reinstall everything and let you know how it goes when I try to use the module.

**Comment by mirrormonark** [comment]
hi. api coinmarketcap is free..
