### ISSUE TITLE
USD Conversion

### ISSUE THREAD

**Issue by BoClow** [SpoturDeal/MMM-crypto-portfolio#18]
Why not include conversion to USD?
This way assets/total assets are displayed in USD.

**Comment by SpoturDeal** [comment]
Please RTFM!

**Comment by BoClow** [comment]
Yes, I see showUSD. Why not include USD in conversion?
showUSD does not display assets/total assets in USD but rather in the currency selected for conversion.
Furthermore, without USD in the conversion list the user is seeing a price displayed in 2 currencies (if they have enabled showUSD), the currency selected in conversion _and_ USD. The option should exist to display _only_ USD here.

**Comment by SpoturDeal** [comment]
Again read the manual


Option | Description
-- | --
conversion | The currency used to convert crypto currency value.Type: stringOptions: AUD, BRL, CAD, CHF, CNY, EUR, GBP, HKD, IDR, INR, JPY, KRW, MXN, RUB|Default: EUR
-- | --

**Comment by BoClow** [comment]
> Again read the manual
> 
> Option	Description
> conversion	The currency used to convert crypto currency value.Type: stringOptions: AUD, BRL, CAD, CHF, CNY, EUR, GBP, HKD, IDR, INR, JPY, KRW, MXN, RUB
> --	--

Am I missing something? I don't see USD in this list...

**Comment by SpoturDeal** [comment]
Did you just try to type USD although it is not in the list?
