### ISSUE TITLE
Add second currency

### ISSUE THREAD

**Issue by lordvalium** [SpoturDeal/MMM-crypto-portfolio#2]
Hi Carel , 
i tried with this code to add a second price / currency. could you test it and commit this in your repo?

```javascript
        var rightCurrencyFormat = this.config.conversion.toLowerCase()

        // rounding the price in Conversion
        var unroundedPrice = apiResult['price_' + rightCurrencyFormat]
        var digitsBeforeDecimalPoint = Math.floor(unroundedPrice).toString().length
        var requiredDigitsAfterDecimalPoint = Math.max(this.config.significantDigits - digitsBeforeDecimalPoint, 2)
        var price = this.roundNumber(unroundedPrice, requiredDigitsAfterDecimalPoint)
        console.log("config.language: " + config.language);

        // add the currency string
        apiResult['price'] = price.toLocaleString(config.language, { style: 'currency', currency: this.config.conversion })
        if (rightCurrencyFormat != 'eur' && this.config.showUSD) {
            // rounding the priceUSD
            var unroundedPriceUSD = apiResult['price_btc']
            var digitsBeforeDecimalPointUSD = Math.floor(unroundedPriceUSD).toString().length
            var requiredDigitsAfterDecimalPointUSD = Math.max(this.config.significantDigits - digitsBeforeDecimalPointUSD, 2)
            var priceUSD = this.roundNumber(unroundedPriceUSD, requiredDigitsAfterDecimalPointUSD)
            apiResult['price'] += ' / ' + unroundedPriceUSD.toLocaleString(config.language, { style: 'currency', currency: 'BTC' })
        }
```

the expected result is (second currency - BTC - is in the yellow box)
![show two prices](https://user-images.githubusercontent.com/2970225/36098093-edf04102-0ffd-11e8-82a2-9ca0913e5bd3.png)

**Comment by SpoturDeal** [comment]
Hello Philipp,

(it is Carel not Carol - not a girl)

I have sent in a new commit. The value against the BTC is now in the details. Not your way. didn't look so nice I have pushed the Column in the table and moved the total column. 
It works fine here. (also added some icons from fontawesome now it looks awesome)

![witbtc](https://user-images.githubusercontent.com/26565921/36100241-e53f3524-1005-11e8-8462-ae27f44698b0.png)

If you can translate the file de.json in the directory translations for me in German I would be very happy. the Δ I use in Dutch is the mathematical description for difference.

**Comment by lordvalium** [comment]
Hi Carel, i just checked your translation. The german is already fine. 
Also the "CHANGE": "% Änderung",is correct. 
With that sign you mean that we subsitute the german word "Änderung" with the mathematical delta sign?

**Comment by SpoturDeal** [comment]
Yes that was my idea it saves room on the screen

Op 12 feb. 2018 17:42 schreef "lordvalium" <notifications@github.com>:

**Comment by lordvalium** [comment]
The MyAsset function is not working for me. 
It shows me 0.36€ and i have 0.045151 BTC in my portfolio. 

Is there a an error with the formating of the number or significant digits?

**Comment by SpoturDeal** [comment]
for what currency is that?

**Comment by lordvalium** [comment]
Closed, removed the toLocale dependencies in the code
