### ISSUE TITLE
Nothing is showing

### ISSUE THREAD

**Issue by MWEL1977** [SpoturDeal/MMM-crypto-portfolio#21]
Hi there,

(Ik kan het ook in het nederlands doen, maar dan snappen de anderen het misschien niet ;) )
At the end of last year (2019) my MagicMirror code broke when I was trying to install the automatic updater module.
Last week I picked it up and made a clean start. Now I'm trying to get this module to work but nothing is showing.
The module is loading and I can see it on the screen but it only shows the headers. Nothing more.
Here is the config part:
{
         		module: "MMM-crypto-portfolio",
            		position: "top_bar",
            		config: {
                		currency: [{name: 'bitcoin',  portf: 1},
					   {name: 'ethereum', portf: 1},
					   {name: 'litecoin', portf: 1}],
                		conversion: "EUR",
				showPortfolio: true,
				showAssets: true,
				showAgainstBTC: true,
				showTotalMarketCap: false,
				showUSD: false,
				fontSize: "small",
				headers: ["change24h", "change1h", "change7d"],
				displayType: "detail",
				showGraphs: true,
				limit: 20
            		}
        	},

I have no ides what's wrong.
Can you help me?

With kind regards,
Mike

**Comment by SpoturDeal** [comment]
https://github.com/SpoturDeal/MMM-crypto-portfolio/blob/master/README.md
Deze app wordt niet meer ondersteund.
