### ISSUE TITLE
Show Global Crypto Market Cap 

### ISSUE THREAD

**Issue by lordvalium** [SpoturDeal/MMM-crypto-portfolio#5]
coinmarketcap gives us with this API request 
https://api.coinmarketcap.com/v1/global/

e.g. that value 

total_market_cap_usd | 430998745319
-- | --

How can i show the **global** crypto market cap in the header instead of the own portfolio?

I dont know how to poll that api and add it to the .js code :(

**Comment by SpoturDeal** [comment]
For the global market cap you need to limit your request at coincap to 2000 
there are at the moment 1800 currencies.

create a loop to read all the market caps from all currencies and add the values

The module is only calculation on the chosen currencies at this moment

**Comment by SpoturDeal** [comment]
Total global market has been added
