### ISSUE TITLE
Possibility to change the exchange?

### ISSUE THREAD

**Issue by lordvalium** [SpoturDeal/MMM-crypto-portfolio#8]
The prices of each exchange differ sometimes a lot. 
is it possible to select a specific exchange for a coin. But optional? 
Does the coinmarketcap api select per default the first in the list?

E.g. i would like to see ETH and ETC for binance. 

Thank you Carel :)

**Comment by SpoturDeal** [comment]
I have looked into several exchanges.
Binance needs auth0 authorization with key and secrets in that case some dependencies are needed to get the module to work.
CoinCap.io has an API that offers the same service as CoinmarketCap however conversion is not implemented.
CryptoCompare and CoinAPI also have a great service, but a very different API and endpoint.

However all services supply the data in a different JSON formats, API requests, API keys. To make this work data conversion needs to be added. It will also need changes in configuration for the user.  I will look into it if there are at least 15 unique supporters for this option.

For some exchanges it might be better to add a separate Module.
